export const questions: string[] = [
      "Write a function to print the name of the class.",
      "Write a function to print the teacher's name.",
      "Write a function to print the names of all the students in the class.",
      "Write a function to print the IDs of all the students in the class.",
      "Write a function to print the subject names for a specific student.",
      "Write a function to print the marks of a specific student in all subjects.",
      "Write a function to calculate and print the average marks for a specific student.",
      "Write a function to calculate and print the total marks for a specific student.",
      "Write a function to calculate and print the average marks for all students in a specific subject.",
      "Write a function to calculate and print the total marks for all students in a specific subject.",
      "Write a function to find and print the student with the highest marks in a specific subject.",
      "Write a function to find and print the student with the lowest marks in a specific subject.",
      "Write a function to find and print the student with the highest total marks.",
      "Write a function to find and print the student with the lowest total marks.",
      "Write a function to find and print the subject with the highest average marks.",
      "Write a function to find and print the subject with the lowest average marks.",
      "Write a function to calculate and print the overall average marks for the class.",
      "Write a function to calculate and print the overall total marks for the class.",
      "Write a function to calculate and print the average marks for each subject.",
      "Write a function to calculate and print the total marks for each subject.",
  ];

